trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubUsername: $(DOCKER_USERNAME)  # DockerHub username secret
  dockerHubPassword: $(DOCKER_PASSWORD)  # DockerHub password secret
  sonarToken: $(SONAR_TOKEN)             # SonarCloud token secret
  sonarProjectKey: '<YOUR_PROJECT_KEY>'  # SonarCloud project key
  sonarOrgKey: '<YOUR_ORG_KEY>'          # SonarCloud organization key

stages:
  - stage: CloneAndBuild
    displayName: 'Clone Repository and Build'
    jobs:
      - job: CloneAndBuildJob
        displayName: 'Clone and Build Node.js App'
        steps:
          # Clone the repo directly
          - task: Checkout@1
            inputs:
              repository: 'https://github.com/fhinkel/nodejs-hello-world.git'
              clean: true
            displayName: 'Clone the Node.js Hello World Repo'

          # Set up Node.js environment
          - task: UseNode@2
            inputs:
              versionSpec: '14.x'
            displayName: 'Set up Node.js'

          # Install dependencies
          - script: |
              npm install
            displayName: 'Install Dependencies'

          # Run tests
          - script: |
              npm test
            displayName: 'Run Tests'

  - stage: SonarCloud
    displayName: 'SonarCloud Analysis'
    jobs:
      - job: SonarQubeAnalysis
        displayName: 'Analyze code with SonarCloud'
        steps:
          - task: SonarCloudAnalyze@1
            inputs:
              organization: $(sonarOrgKey)
              projectKey: $(sonarProjectKey)
              token: $(sonarToken)
            displayName: 'Run SonarCloud Analysis'

  - stage: Docker
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: DockerBuildPush
        displayName: 'Build and Push Docker Image to DockerHub'
        steps:
          # Log in to DockerHub
          - task: Docker@2
            inputs:
              containerRegistry: $(dockerHubUsername)
              repository: 'yourusername/nodejs-hello-world'
              command: 'login'
              dockerRegistryEndpoint: 'DockerHub'
            displayName: 'Login to DockerHub'

          # Build the Docker image and push to DockerHub
          - task: Docker@2
            inputs:
              containerRegistry: $(dockerHubUsername)
              repository: 'yourusername/nodejs-hello-world'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: 'latest'
            displayName: 'Build and Push Docker Image'

  - stage: Deploy
    displayName: 'Run Docker Image Locally'
    jobs:
      - job: RunDockerImage
        displayName: 'Run Docker Image Locally'
        steps:
          - script: |
              docker login -u $(dockerHubUsername) -p $(dockerHubPassword)
              docker pull $(dockerHubUsername)/nodejs-hello-world:latest
              docker run -d -p 8080:8080 $(dockerHubUsername)/nodejs-hello-world:latest
            displayName: 'Pull and Run Docker Image Locally'
